#!/bin/sh

PLASMA_DARK=CatppuccinMochaFlamingo
PLASMA_LIGHT=CatppuccinLatteFlamingo
CURSOR_DARK=Breeze_Light
CURSOR_LIGHT=breeze_cursors
ICON_DARK=breeze-dark
ICON_LIGHT=breeze
WALLPAPER_LIGHT=/home/niranjan/pictures/wallpapers/win11-flow-blue-dark/light.jpg
WALLPAPER_DARK=/home/niranjan/pictures/wallpapers/win11-flow-blue-dark/dark.png

BIN_PLASMA=plasma-apply-colorscheme
BIN_CURSOR=plasma-apply-cursortheme
BIN_WALLPAPER=plasma-apply-wallpaperimage

if [ "x$(qdbus org.freedesktop.portal.Desktop /org/freedesktop/portal/desktop org.freedesktop.portal.Settings.Read org.freedesktop.appearance color-scheme)" = x1 ]; then
    echo "dark mode"
	plasmacolors=$PLASMA_LIGHT
	cursorcolors=$CURSOR_LIGHT
	wallpaper=$WALLPAPER_LIGHT
fi

if [ "x$(qdbus org.freedesktop.portal.Desktop /org/freedesktop/portal/desktop org.freedesktop.portal.Settings.Read org.freedesktop.appearance color-scheme)" = x2 ]; then
    echo "light mode"
	plasmacolors=$PLASMA_DARK
	cursorcolors=$CURSOR_DARK
	wallpaper=$WALLPAPER_DARK
fi

$BIN_PLASMA $plasmacolors
$BIN_CURSOR $cursorcolors
$BIN_ICON $iconcolors
$BIN_WALLPAPER $wallpaper
